---
abstract: 'css inliner'
author:
  - 'Tokuhiro Matsuno <tokuhirom+cpan@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-DoCoMoCSS
no_index:
  directory:
    - inc
    - t
requires:
  CSS::Tiny: 0
  CSS::Tiny::Style: 0
  Carp: 0
  File::Spec: 0
  Filter::Util::Call: 0
  HTML::Selector::XPath: 0
  XML::LibXML: 1.61
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
