abstract: css inliner
author: Tokuhiro Matsuno <tokuhirom+cpan@gmail.com>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: HTML-DoCoMoCSS
no_index: 
  directory: 
    - inc
    - t
requires: 
  CSS::Tiny: 0
  CSS::Tiny::Style: 0
  Carp: 0
  File::Spec: 0
  HTML::Selector::XPath: 0
  XML::LibXML: 0
version: 0.01
